[tool.poetry]
name = "04-deployment"
version = "0.1.0"
description = ""
authors = ["Emanuel Tom√© <emanuelrstome@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
scikit-learn = "^1.5.0"
numpy = "^2.0.0"
fastparquet = "^2024.5.0"
pyarrow = "^16.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
